import "./extension.test";
import "./architectureFactsScanner.test";
import "./analysisTiming.test";
import "./codexActivityProvider.test";
import "./doctorUbuntu.test";
import "./featureMapper.test";
import "./fileAnalysisCache.test";
import "./gitProvider.test";
import "./graphDiff.test";
import "./graphGeometry.test";
import "./graphViews.test";
import "./importResolverIndex.test";
import "./importParser.test";
import "./legacyRendererRemoval.test";
import "./liveChangeInputs.test";
import "./moduleRoleInference.test";
import "./riskScorer.test";
import "./scanPathFilter.test";
import "./scannerBackendSelection.test";
import "./semanticArchitectureModel.test";
import "./storage.test";
import "./ubuntuPathKind.test";
import "./vscodeConfigUbuntu.test";
import "./webviewAssets.test";
import "./workspaceIndex.test";

console.log("All unit checks passed.");
