import * as fs from "fs";
import * as path from "path";
import { createMockDashboardState } from "../src/mockData/mockDashboardState";
import { DashboardMode } from "../src/webview/dashboardState";
import { renderStandaloneDashboardHtml } from "../src/webview/standaloneHtml";

interface SnapshotTarget {
  mode: DashboardMode;
  htmlFileName: string;
  pngFileName: string;
}

const repoRoot = path.resolve(__dirname, "..", "..");
const artifactsRoot = path.join(repoRoot, "artifacts");
const uiRoot = path.join(artifactsRoot, "ui");

const snapshotTargets: SnapshotTarget[] = [
  {
    mode: "liveChanges",
    htmlFileName: "live-changes.html",
    pngFileName: "live-changes.png"
  },
  {
    mode: "wholeArchitecture",
    htmlFileName: "whole-architecture.html",
    pngFileName: "whole-architecture.png"
  },
  {
    mode: "featureFocus",
    htmlFileName: "feature-focus.html",
    pngFileName: "feature-focus.png"
  },
  {
    mode: "diffSinceBaseline",
    htmlFileName: "diff-since-baseline.html",
    pngFileName: "diff-since-baseline.png"
  }
];

fs.mkdirSync(uiRoot, { recursive: true });

for (const target of snapshotTargets) {
  const state = createMockDashboardState(target.mode);
  const html = renderStandaloneDashboardHtml(state);
  fs.writeFileSync(path.join(uiRoot, target.htmlFileName), html, "utf8");
}

fs.writeFileSync(path.join(artifactsRoot, "validation-report.md"), renderValidationReport(), "utf8");

console.log(`Rendered ${snapshotTargets.length} standalone dashboard HTML snapshots to ${uiRoot}`);
console.log(`Wrote validation report to ${path.join(artifactsRoot, "validation-report.md")}`);

function renderValidationReport(): string {
  const htmlPaths = snapshotTargets.map((target) => `- artifacts/ui/${target.htmlFileName}`).join("\n");
  const pngPaths = snapshotTargets.map((target) => `- artifacts/ui/${target.pngFileName}`).join("\n");

  return `# Live Architecture Map Validation Report

Generated: ${new Date().toISOString()}

Source of truth: react_plan_v8.md

## Commands

- npm install
- npx playwright install chromium
- npm run compile
- npm run visual:render
- npm run visual:test
- npm run test:vscode

## Results

- Compile result: passed before snapshot rendering because npm run visual:render invokes npm run compile first.
- Unit test result: not run in the requested command sequence.
- Visual render result: passed; this report was generated by scripts/render-ui-snapshots.ts using the Vite-built React webview bundle.
- Visual test result: pending until npm run visual:test completes.
- VS Code integration test result: pending until npm run test:vscode completes.

## Generated Artifacts

Standalone HTML:

${htmlPaths}

Expected Playwright screenshots:

${pngPaths}

## Live VS Code Screenshot Capture

Attempted: no.

Reason: optional live Extension Development Host screenshot capture is not part of the requested automated command sequence for this pass. Standalone Playwright HTML screenshots are the primary validation evidence.

## Target Workspace Safety

No inspected target workspace files were written. This first pass writes only inside the extension repository, with generated validation output under ignored artifacts/.
`;
}
